# Generated by Django 5.2.8 on 2025-11-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_series_car_series'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
