# Generated by Django 5.2.8 on 2025-11-21 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_series_serie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='series',
            new_name='serie',
        ),
        migrations.RemoveField(
            model_name='car',
            name='series',
        ),
        migrations.AddField(
            model_name='car',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car_serie', to='cars.serie'),
        ),
    ]
